#ifndef COMMON_VARIABLES_H
#define COMMON_VARIABLES_H

#define DISPLAY_WIDTH 1080
#define DISPLAY_HEIGHT 1920
#define ROCKET_WIDTH 250
#define ROCKET_HEIGHT 250
#define ROCKET_TOLERANCE_WIDTH 20 //MARGIN ON THE LEFT AND RIGHT
#define ROCKET_TOLERANCE_HEIGHT 700 //MARGIN FROM THE BOTTOM
#define LEFT_RIGHT_MIN_HEIGHT 200
#define ENGINE_WIDTH 215
#define ENGINE_HEIGHT 300
#define ENEMY_ROCK_WIDTH 300
#define ENEMY_ROCK_HEIGHT 246

#endif // COMMON_VARIABLES_H
